### PR TITLE
Added new workflow for version bump

### PR DESCRIPTION
**Pull request by plon-Susk7**
This PR is associated with #440 

1. Made change to merge-main.yml file.
2. Made changes to pyproject.toml file. The new block specifically catered for semantic release looks like this. version_toml is necessary for automatically updating version of the toml file.
```
[tool.semantic_release.branches.main]
version_variable = ["pyproject.toml:project.version"]
version_toml = ["pyproject.toml:project.version"]
branch = "main"
tag_format = "feluda-{version}"
```

### CODE REVIEW

**Comment by plon-Susk7** [comment]
## Setup

1. Make sure UV is installed
2. Install packages

```sh
uv pip install .
uv pip install ".[dev]"
```

3. install pre-commit hooks

```sh
pre-commit install --hook-type commit-msg
# verify the install
ls -a .git/hooks
```
The workflow was tested in https://github.com/aatmanvaidya/feluda-versioning-check.
Major credits to @aatmanvaidya

**Comment by dennyabrain** [comment]
@plon-Susk7 @aatmanvaidya Can we create a document in wiki called "Release Workflow" or something to explain a bunch of things : 
1. Overview of how feluda manages its release and the internal plugins release
2. How is semantic versioning followed
3. What commit conventions should a contributor follow
4. Upon merging a PR into main, what workflows are triggered and an explanation of what they do
5. Add links to pypi pages
6. Any other relevant information

**Comment by aatmanvaidya** [comment]
@dennyabrain yes this has been on my to-do list, we will do this
- we plan to explain the release workflow (the entire process of semantic versioning) in the [Release Management](https://github.com/tattle-made/feluda/wiki/Release-Management) wiki.
- we plan to add everything that a contributor should follow and things that will help them (conventional commits, link to the dummy repo etc) to the "Developer Documentation for Setting up Feluda Locally" and in the `CONTRIBUTING.md`.

just to summarise, the plan is to document everything done properly and at the right places.

**Comment by dennyabrain** [comment]
Perfect. This is looking great @aatmanvaidya @plon-Susk7. Great job on this.

**Pull request merged**
