### PR TITLE
feat: audio operator to extract embedding vectors

### PR DESCRIPTION
**Pull request by aatmanvaidya**
This PR address - https://github.com/tattle-made/DAU_tipline/issues/21
- adds an operator that extracts embedding vectors from an audio file
- adds an test for the operator

### CODE REVIEW

**Comment by dennyabrain** [comment]
@aatmanvaidya can you please create documentation for it? if nothing just link to the reference article on elastic site.

**Comment by aatmanvaidya** [comment]
@dennyabrain yes that is due, I will document everything on the issue

**Comment by dennyabrain** [comment]
Do that but do add consise documentation like other operators on how to install,test this operator.

**Comment by aatmanvaidya** [comment]
have documented everything here - https://github.com/tattle-made/DAU_tipline/issues/21#issuecomment-1932056828

**Pull request merged**
