### PR TITLE
feat: add operator to detect language in an audio file

### LINKED ISSUE #316: Operator to detect language in an Audio file
Operators are core components of Feluda, they are modules that help us analyse media items - text, image, video, audio etc. All the code for operators can be found at `src/core/operators`

The task is to create a Operator that can **detect language** in a Audio media item. This is an open ended issue, you will have to investigate on what methods to do this are best and effective. 
For now the operator should be able to identify/detect the `English`, `Hindi`, `Telugu` and `Tamil` languages. 

## Expected Outcome
- Write an operator, profile it for RAM and CPU usage. A key outcome should be that the operator should have stabilised RAM usage. Some methods on profiling have been documented on the Wiki [here](https://github.com/tattle-made/feluda/wiki/Optimization).
- Write a test for the operator
- Document the operator on the Wiki

### PR DESCRIPTION
**Pull request by Snehil-Shah**
Resolves #316 

### Approach

- Used this [VAD](https://github.com/snakers4/silero-vad) for detecting and extracting speech from the audio as whisper trims/pads the audio to fit 30 seconds.
- Whisper then detects the language and returns the ISO 639-1 language code. I have also added a map between the codes and their generic names.

### Research

- Compared two language detection models on various benchmarks (whisper and a pre-trained speechbrain model) [here](https://www.kaggle.com/code/snehi1shah/benchmarking-language-detection-models)
*Conducted three tests:*
  - Accuracy with english, hindi, tamil and telugu
  - Accuracy with noisy audio
  - Runtime performance

  The notebook contains detailed inferences and opinions on why I chose whisper, we can change it if you have a differing conclusion.

- A small [notebook](https://colab.research.google.com/drive/14YADtTMMEWGVHRHg2KCrkVGF5lqCT1Ul?usp=sharing) depicting the need of using a VAD

### Benchmarks

***Updated in the comments***

### Questions

@aatmanvaidya I am a bit confused as to where can I update the wiki for this operator, would appreciate some help..

### CODE REVIEW

**Comment by aatmanvaidya** [comment]
Hi @Snehil-Shah , great effort!

give us some time, we will get back to you with detailed comments and feedback on this

regarding the documentation, we are still in process of moving the docs to the Wiki, I will also get back to you on that!

**Comment by aatmanvaidya** [comment]
Hi @Snehil-Shah , 

1. Here are the commands to generate the requirements.txt file - 
```sh
$ cd src/core/operators
$ pip install --upgrade pip-tools
$ TMPDIR=<temp_dir> pip-compile --verbose --allow-unsafe --generate-hashes --emit-index-url --emit-find-links <YOUR_REQUIRMENTS.IN_FILE>
```
Let me know if you need any help with this, I can also do this for you and push code to this PR. 

2. Here is some previous work I had done to profile an operator - https://github.com/tattle-made/DAU/issues/42#issuecomment-1938317649
   - So you can find the `Time Taken` by just using `time.time()` as listed on the wiki - so something like this
```python
import time

start_time = time.time()
# The function of the operator to profile
run(file_path)
end_time = time.time()
duration = end_time - start_time
print(duration)
```
    - and you can find the RAM usage using Memray itself - https://github.com/tattle-made/feluda/wiki/Optimization#memory-profiling. So once you generate the html file of the `Flamegraph` and if you hover over `run()` function in it, you will be able to see the RAM usage. 

Let me know if you need any help in this!

**Comment by Snehil-Shah** [comment]
OK, made some changes and improvements as you can see from the commit log

### Operator Profile

1. **CPU time**: calculated using both `time` and `pyinstrument`:
image

2. **RAM usage**: calculated using `memray`:
image

### Results:

| Audio Length | CPU Time (s) | RAM Usage |
|---|---|---|
| 10s | 1.61 | 214.0MiB |
| 30s | 2.33 | 215.8MiB |
| 1m | 3.46 | 218.6MiB |
| 5m | 12.14 | 275.8MiB |
| 10m | 23.20 | 550.6MiB |
| 30m | 66 | 1.6GiB |

**Comment by aatmanvaidya** [comment]
Hi @Snehil-Shah overall things look good!

I will just run and test this out locally on my machine once, give me some time for that!

**Review by aatmanvaidya — APPROVED** [review]

**Comment by aatmanvaidya** [comment]
Hi @Snehil-Shah , have merged the PR, can you also just paste the CPU and RAM profiling results on the issue?

**Pull request merged**
